export const TopTierBrandData = [
    // 🍎 Apple (10 products)
    {
      id: 1,
      image: "/Products/Mouse.png",
      title: "Logitech G502 X Gaming Mouse (White)",
      rating: 4.0,
      price: 4700,
      mrp: 5900,
      discount: 30,
      brand: "apple",
    },
    {
      id: 2,
      image: "/Products/gaming-chair.png",
      title: "Razer DeathAdder V2 Gaming Mouse",
      rating: 4.5,
      price: 3200,
      mrp: 3999,
      discount: 20,
      brand: "apple",
    },
    {
      id: 9,
      image: "/Products/asus-tuf.png",
      title: "Apple Magic Mouse 2 (Wireless, Rechargable)",
      rating: 4.6,
      price: 7200,
      mrp: 7999,
      discount: 10,
      brand: "apple",
    },
    {
      id: 10,
      image: "/Products/Mouse.png",
      title: "Apple Magic Trackpad 2",
      rating: 4.7,
      price: 11500,
      mrp: 12999,
      discount: 12,
      brand: "apple",
    },
    {
      id: 11,
      image: "/Products/gaming-chair.png",
      title: "Apple Wireless Keyboard and Mouse Combo",
      rating: 4.2,
      price: 8800,
      mrp: 9999,
      discount: 10,
      brand: "apple",
    },
    {
      id: 12,
      image: "/Products/asus-tuf.png",
      title: "Apple Magic Keyboard with Touch ID",
      rating: 4.8,
      price: 12500,
      mrp: 13999,
      discount: 11,
      brand: "apple",
    },
    {
      id: 13,
      image: "/Products/Mouse.png",
      title: "Apple Pencil (2nd Generation)",
      rating: 4.9,
      price: 9500,
      mrp: 10999,
      discount: 14,
      brand: "apple",
    },
    {
      id: 14,
      image: "/Products/gaming-chair.png",
      title: "Apple Smart Keyboard Folio",
      rating: 4.5,
      price: 15500,
      mrp: 17999,
      discount: 13,
      brand: "apple",
    },
    {
      id: 15,
      image: "/Products/asus-tuf.png",
      title: "Apple USB-C Digital AV Multiport Adapter",
      rating: 4.3,
      price: 5900,
      mrp: 6999,
      discount: 16,
      brand: "apple",
    },
    {
      id: 16,
      image: "/Products/Mouse.png",
      title: "Apple MagSafe Charger",
      rating: 4.7,
      price: 4300,
      mrp: 4999,
      discount: 14,
      brand: "apple",
    },
  
    // 🖥️ HP (10 products)
    {
      id: 3,
      image: "/Products/asus-tuf.png",
      title: "SteelSeries Rival 650 Wireless Gaming Mouse",
      rating: 4.3,
      price: 7500,
      mrp: 8999,
      discount: 15,
      brand: "hp",
    },
    {
      id: 7,
      image: "/Products/Mouse.png",
      title: "Glorious Model O Gaming Mouse (Black)",
      rating: 4.4,
      price: 5400,
      mrp: 6299,
      discount: 14,
      brand: "hp",
    },
    {
      id: 17,
      image: "/Products/gaming-chair.png",
      title: "HP X3000 G2 Wireless Mouse",
      rating: 4.1,
      price: 1500,
      mrp: 1999,
      discount: 25,
      brand: "hp",
    },
    {
      id: 18,
      image: "/Products/asus-tuf.png",
      title: "HP OMEN Reactor Wired Optical Gaming Mouse",
      rating: 4.5,
      price: 7200,
      mrp: 8500,
      discount: 15,
      brand: "hp",
    },
    {
      id: 19,
      image: "/Products/Mouse.png",
      title: "HP X500 Wired Optical Mouse",
      rating: 4.0,
      price: 600,
      mrp: 999,
      discount: 40,
      brand: "hp",
    },
    {
      id: 20,
      image: "/Products/gaming-chair.png",
      title: "HP Pavilion Gaming Mouse 300",
      rating: 4.3,
      price: 1800,
      mrp: 2299,
      discount: 21,
      brand: "hp",
    },
    {
      id: 21,
      image: "/Products/asus-tuf.png",
      title: "HP Z5000 Bluetooth Wireless Mouse",
      rating: 4.2,
      price: 2500,
      mrp: 2999,
      discount: 16,
      brand: "hp",
    },
    {
      id: 22,
      image: "/Products/Mouse.png",
      title: "HP Comfort Grip Wireless Mouse",
      rating: 4.1,
      price: 3200,
      mrp: 3799,
      discount: 15,
      brand: "hp",
    },
    {
      id: 23,
      image: "/Products/gaming-chair.png",
      title: "HP Spectre Rechargeable Mouse 700",
      rating: 4.7,
      price: 4900,
      mrp: 5999,
      discount: 18,
      brand: "hp",
    },
    {
      id: 24,
      image: "/Products/asus-tuf.png",
      title: "HP USB Fingerprint Mouse",
      rating: 4.5,
      price: 5700,
      mrp: 6999,
      discount: 19,
      brand: "hp",
    },
  
    // 🖥️ Acer (10 products)
    {
      id: 4,
      image: "/Products/Mouse.png",
      title: "Corsair Harpoon RGB Pro Gaming Mouse",
      rating: 3.8,
      price: 2500,
      mrp: 2999,
      discount: 16,
      brand: "acer",
    },
    {
      id: 8,
      image: "/Products/gaming-chair.png",
      title: "ASUS ROG Chakram Core Gaming Mouse",
      rating: 4.1,
      price: 6700,
      mrp: 7999,
      discount: 16,
      brand: "acer",
    },
    {
      id: 25,
      image: "/Products/asus-tuf.png",
      title: "Acer Predator Cestus 330 Gaming Mouse",
      rating: 4.2,
      price: 6200,
      mrp: 7499,
      discount: 17,
      brand: "acer",
    },
    {
      id: 26,
      image: "/Products/Mouse.png",
      title: "Acer Wireless Optical Mouse M501",
      rating: 4.0,
      price: 1200,
      mrp: 1599,
      discount: 25,
      brand: "acer",
    },
    {
      id: 27,
      image: "/Products/gaming-chair.png",
      title: "Acer Predator Gaming Mousepad",
      rating: 4.3,
      price: 2200,
      mrp: 2499,
      discount: 12,
      brand: "acer",
    },
    {
      id: 28,
      image: "/Products/asus-tuf.png",
      title: "Acer Ergonomic Mouse AMR020",
      rating: 3.9,
      price: 1800,
      mrp: 2199,
      discount: 18,
      brand: "acer",
    },
    {
      id: 29,
      image: "/Products/Mouse.png",
      title: "Acer Predator Galea 310 Gaming Headset",
      rating: 4.4,
      price: 5100,
      mrp: 5999,
      discount: 15,
      brand: "acer",
    },
    {
      id: 30,
      image: "/Products/gaming-chair.png",
      title: "Acer Predator Aethon 300 Gaming Keyboard",
      rating: 4.6,
      price: 7400,
      mrp: 8999,
      discount: 17,
      brand: "acer",
    },
    {
      id: 31,
      image: "/Products/asus-tuf.png",
      title: "Acer Nitro Mouse M101",
      rating: 4.2,
      price: 1900,
      mrp: 2299,
      discount: 18,
      brand: "acer",
    },
    {
      id: 32,
      image: "/Products/Mouse.png",
      title: "Acer Predator Cestus 500 RGB Mouse",
      rating: 4.5,
      price: 8900,
      mrp: 9999,
      discount: 11,
      brand: "acer",
    },
  
    // 🖥️ ASUS (10 products)
    {
      id: 5,
      image: "/Products/gaming-chair.png",
      title: "HyperX Pulsefire Surge RGB Gaming Mouse",
      rating: 4.2,
      price: 3900,
      mrp: 4599,
      brand: "asus",
    },
    {
      id: 33,
      image: "/Products/asus-tuf.png",
      title: "ASUS TUF Gaming M4 Air",
      rating: 4.4,
      price: 3400,
      mrp: 3999,
      discount: 15,
      brand: "asus",
    },
    {
      id: 34,
      image: "/Products/Mouse.png",
      title: "ASUS ROG Gladius III Wireless",
      rating: 4.6,
      price: 7200,
      mrp: 7999,
      discount: 10,
      brand: "asus",
    },
    {
      id: 35,
      image: "/Products/gaming-chair.png",
      title: "ASUS ROG Spatha X Wireless Gaming Mouse",
      rating: 4.7,
      price: 11000,
      mrp: 12999,
      discount: 15,
      brand: "asus",
    },
    {
      id: 36,
      image: "/Products/asus-tuf.png",
      title: "ASUS TUF Gaming K5 Keyboard",
      rating: 4.5,
      price: 4600,
      mrp: 5299,
      discount: 13,
      brand: "asus",
    },
    {
      id: 37,
      image: "/Products/Mouse.png",
      title: "ASUS ROG Strix Impact II Gaming Mouse",
      rating: 4.2,
      price: 3700,
      mrp: 4499,
      discount: 18,
      brand: "asus",
    },
    {
      id: 38,
      image: "/Products/gaming-chair.png",
      title: "ASUS ROG Strix Evolve Gaming Mouse",
      rating: 4.1,
      price: 5100,
      mrp: 5999,
      discount: 15,
      brand: "asus",
    },
    {
      id: 39,
      image: "/Products/asus-tuf.png",
      title: "ASUS Cerberus Optical Gaming Mouse",
      rating: 3.9,
      price: 2700,
      mrp: 3299,
      discount: 18,
      brand: "asus",
    },
    {
      id: 40,
      image: "/Products/Mouse.png",
      title: "ASUS ROG Pugio II Wireless Mouse",
      rating: 4.6,
      price: 9500,
      mrp: 10999,
      discount: 14,
      brand: "asus",
    },
  
    // 🖥️ Dell (10 products)
    {
      id: 6,
      image: "/Products/asus-tuf.png",
      title: "Logitech MX Master 3 Wireless Mouse",
      rating: 4.8,
      price: 8900,
      mrp: 10999,
      discount: 19,
      brand: "dell",
    },
    {
      id: 41,
      image: "/Products/Mouse.png",
      title: "Dell WM126 Wireless Mouse",
      rating: 4.2,
      price: 1600,
      mrp: 1999,
      discount: 20,
      brand: "dell",
    },
    {
      id: 42,
      image: "/Products/gaming-chair.png",
      title: "Dell MS116 Optical Wired Mouse",
      rating: 4.1,
      price: 700,
      mrp: 999,
      discount: 30,
      brand: "dell",
    },
    {
      id: 43,
      image: "/Products/asus-tuf.png",
      title: "Dell Premier Wireless Mouse WM527",
      rating: 4.5,
      price: 5200,
      mrp: 5999,
      discount: 13,
      brand: "dell",
    },
    {
      id: 44,
      image: "/Products/Mouse.png",
      title: "Dell Mobile Pro Wireless Mouse MS5120W",
      rating: 4.6,
      price: 3700,
      mrp: 4499,
      discount: 18,
      brand: "dell",
    },
    {
      id: 45,
      image: "/Products/gaming-chair.png",
      title: "Dell Alienware Wired/Wireless Gaming Mouse AW610M",
      rating: 4.7,
      price: 8700,
      mrp: 9999,
      discount: 13,
      brand: "dell",
    },
    {
      id: 46,
      image: "/Products/asus-tuf.png",
      title: "Dell Laser Wired Mouse",
      rating: 4.0,
      price: 1100,
      mrp: 1599,
      discount: 31,
      brand: "dell",
    },
    {
      id: 47,
      image: "/Products/Mouse.png",
      title: "Dell Wireless Keyboard and Mouse Combo",
      rating: 4.4,
      price: 4100,
      mrp: 4999,
      discount: 18,
      brand: "dell",
    },
    {
      id: 48,
      image: "/Products/gaming-chair.png",
      title: "Dell USB-C Mobile Adapter with Mouse",
      rating: 4.5,
      price: 6700,
      mrp: 7999,
      discount: 16,
      brand: "dell",
    },
    {
      id: 49,
      image: "/Products/asus-tuf.png",
      title: "Dell Alienware AW310M Gaming Mouse",
      rating: 4.6,
      price: 7600,
      mrp: 8999,
      discount: 15,
      brand: "dell",
    },
  ];
  