import type { Metadata } from "next";
import "./globals.css";
import { gotham, inter } from "./fonts";
import { Toaster } from "react-hot-toast";
import { StoreProvider } from "./provider";
import UserLayout from "@/components/Layouts/UserLayout";

export const metadata: Metadata = {
  title: "360 Electronics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className={`antialiased`}>
        <StoreProvider>
          <UserLayout>
            <Toaster />
            {children}
          </UserLayout>
        </StoreProvider>
      </body>
    </html>
  );
}
