import type { Metadata } from "next";
import "./globals.css";
import { gotham } from "./fonts";
import { Providers } from "./providers";


export const metadata: Metadata = {
  title: "360 Electronics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={gotham.className}>
      <body
        className={`antialiased`}
      >
        <Providers>

          {children}
        </Providers>
      </body>
    </html>
  );
}
